changelog:
  exclude:
    labels:
      - 'skip-changelog'
  categories:
    - title: 'Features'
      labels:
        - 'add'
        - 'feature'
        - 'enhancement'
    - title: 'Bug Fixes'
      labels:
        - 'fix'
        - 'bug'
    - title: 'Other Changes'
      labels:
        - '*'